# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
                ('college_intake', models.CharField(max_length=300)),
                ('college_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_turnover', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=400)),
                ('deptartment_information', models.CharField(max_length=500)),
                ('department_coresubject', models.CharField(max_length=500)),
                ('department_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Departments'),
        ),
        migrations.AddField(
            model_name='college',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Departments'),
        ),
    ]
