# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
